version: "3.7"

services:

  school-project-db:
    image: mysql
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: schooldb!
      MYSQL_DB: demo
