spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://my-rds.cshttetfsiot.ap-northeast-2.rds.amazonaws.com:3306/demo?createDatabaseIfNotExist=true&characterEncoding=utf8
    username: admin
    password: schooldb!

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: create
server:
  port: 8081
